server {
    listen 80;
    server_name app.realty-catalog.local;

    location / {
        proxy_pass http://realty-catalog-website-prod:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}